// certificatic/sesion08/prueba-vue-cli/src/components/TodoItem.vue
<template>
    <div>
        <h1>{{mensaje}}</h1>
        <input 
            type="checkbox"
            v-bind:checked="todo.completed"
            v-on:change="$emit('mark-complete')"

        />

        <label>
          {{todo.title}}
        </label>
        <button 
            v-on:click="$emit('delete-todo')"
        />
            
    </div>
</template>

<script>
export default {
    name: 'TodoItem',
     props:{
            todo:Array,
            mensaje:String
    }    
}
</script>

<style>

</style>

// Tutoriales/scrimba/32-react-state-practice-2/src/components/TodoItem.js
import React from 'react'

class TodoItem extends React.Component{
    render(){
        return(
            <div>
                <input
                    onChange={() => this.props.handleClick(this.props.item.id)}
                    type="checkbox"
                    checked={this.props.item.completed}
                />
                <label>{this.props.item.id} {this.props.item.activity}</label>
            </div>
        )
    }
}
export default TodoItem
