// sesion08/prueba-vue-cli/src/components/TodoList.vue
<template>
    <ul>
        <li 
            v-for="todo in todos"
            v-bind:key="todo.id"
            
        >
            
        
        <TodoItem 
            v-bind:mensaje="mensaje2"
            v-bind:todo='todo'
            v-on:mark-complete="marcadoCompleto"
        ></TodoItem>
        </li>
    </ul>
</template>

<script>
    import TodoItem from '@/components/TodoItem'
    export default {
        name:'TodoList',
        props:{
            mensaje2:String,
            todos:Array    
        },
        components:{
            TodoItem
        }, 
        methods:{
            marcadoCompleto(){
                return "<h1>hola</h1>"
            }

        }
        
    }
</script>

<style>

</style>

// certificatic/sesion12/react-todo-list/src/components/TodoList.js
import React from 'react';
import TodoItem from './TodoItem'

export default function TodoList(props) {
    return (
        props.todos.map(
            todo => 
                <TodoItem
                    key={todo.id}
                    todo={todo} 
                    markComplete={props.markComplete}
                />
        )
    );
}
